name: Publish to IPFS

on:
  push:
    branches:
      - main  # Replace with your GitHub Pages source branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to IPFS via Pinata
      uses: aquiladev/ipfs-action@v0.1.3
      with:
        path: ./  # The root directory of your repository
        service: pinata
        pinataKey: ${{ secrets.PINATA_API_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET_API_KEY }}
        pinataPinName: my_unique_pin_name  # Replace with a name you choose
