name: Publish to IPFS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to IPFS via Pinata
    - uses: aquiladev/ipfs-action@v0.1.3
      id: pinata
      with:
        path: ./  # The root directory of your repository
        service: pinata
        pinataKey: ${{ secrets.PINATA_API }}
        pinataSecret: ${{ secrets.PINATA_API_KEY }}
        pinataPinName: dotpicspinata
